### ISSUE TITLE
example can not be run

### ISSUE THREAD

**Issue by maiermic** [vardius/peer-data-server#16]
The [example](https://github.com/vardius/peer-data-server/wiki) contains a syntax error (remove `}` near the end)

```js
app.get("*", (req, res) => res.sendFile(index)});
```

and uses `import` syntax that is not supported by Node.js out of the box [yet](https://nodejs.org/api/esm.html). `require` would be used instead, but using

```js
const PeerDataServer = require("peer-data-server");
PeerDataServer(server);
```

results in an error

> TypeError: PeerDataServer is not a function

Instead you have to access the `default` property

```js
const PeerDataServer = require("peer-data-server").default;
PeerDataServer(server);
```

which seems unnecessary to me, since there is only a single export :wink: It should be at least documented.

**Comment by vardius** [comment]
updated usage example: https://github.com/vardius/peer-data-server/wiki/Home/cdb1d243567d2e89073c3a7dc9a897bd3cbf960a

**Comment by maiermic** [comment]
In which case does `default` not exist?

```js
const PeerDataServer = require("peer-data-server");
// ...
const appendPeerDataServer = PeerDataServer.default || PeerDataServer;
```

**Comment by vardius** [comment]
I don't remember why I did it like that to be honest.
copied example from: https://github.com/vardius/react-webrtc-chat/blob/master/server.js

**Comment by maiermic** [comment]
Anyhow, thanks for the quick fix :+1:
